---
# Source: mcm-deploy/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: machine-controller-manager
---
# Source: mcm-deploy/templates/rbac/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: machine-controller-manager
  namespace: machine-controller-manager
  labels:

    helm.sh/chart: mcm-deploy-0.2.1
    app.kubernetes.io/name: mcm-deploy
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.1.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: mcm-deploy/templates/rbac/control-cluster-role.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: machine-controller-manager-control
rules:
-  apiGroups:
   - machine.sapcloud.io
   resources:
   - awsmachineclasses
   - azuremachineclasses
   - gcpmachineclasses
   - openstackmachineclasses
   - alicloudmachineclasses
   - packetmachineclasses
   - machinedeployments
   - machines
   - machinesets
   - machineclasses
   - machines/status
   - machines/status
   - machinesets/status
   - machinedeployments/status
   verbs:
   - create
   - delete
   - deletecollection
   - get
   - list
   - patch
   - update
   - watch
-  apiGroups:
   - ""
   resources:
   - nodes
   - nodes/status
   - configmaps
   - secrets
   - endpoints
   - events
   verbs:
   - create
   - delete
   - deletecollection
   - get
   - list
   - patch
   - update
   - watch
---
# Source: mcm-deploy/templates/rbac/target-cluster-role.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: machine-controller-manager-target
rules:
-  apiGroups:
   - ""
   resources:
   - nodes
   - endpoints
   - replicationcontrollers
   - pods
   verbs:
   - create
   - delete
   - deletecollection
   - get
   - list
   - patch
   - update
   - watch
-  apiGroups:
   - ""
   resources:
   - pods/eviction
   verbs:
   - create
-  apiGroups:
   - extensions
   - apps
   resources:
   - replicasets
   - statefulsets
   - daemonsets
   - deployments
   verbs:
   - create
   - delete
   - deletecollection
   - get
   - list
   - patch
   - update
   - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - persistentvolumes
  verbs:
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - watch
  - list
- apiGroups:
  - storage.k8s.io
  resources:
  - volumeattachments
  verbs:
  - get
  - list
  - watch
---
# Source: mcm-deploy/templates/rbac/control-cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: machine-controller-manager-control
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: machine-controller-manager-control
subjects:
- kind: ServiceAccount
  name: machine-controller-manager
  namespace: machine-controller-manager
---
# Source: mcm-deploy/templates/rbac/target-cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: machine-controller-manager-target
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: machine-controller-manager-target
subjects:
- kind: ServiceAccount
  name: machine-controller-manager
  namespace: machine-controller-manager
---
# Source: mcm-deploy/templates/mcm/deployment-mcm.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: machine-controller-manager
  labels:
    helm.sh/chart: mcm-deploy-0.2.1
    app.kubernetes.io/name: mcm-deploy
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.1.0"
    app.kubernetes.io/managed-by: Helm  
  namespace: machine-controller-manager
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: machine-controller-manager
  template:
    metadata:
      labels:
        app: machine-controller-manager
    spec:
      containers:
        - name: machine-controller-manager
          image: "registry.ske.eu01.stackit.cloud/gardener-ds/machine-controller-manager:v0.39.0-ske-1-720b026c"
          imagePullPolicy: IfNotPresent
          command:
            - ./machine-controller-manager
            - '--control-kubeconfig=inClusterConfig'
            - '--namespace=machine-controller-manager'
            - '--port=10258'
            - '--safety-up=2'
            - '--safety-down=1'
            - '--machine-drain-timeout=5m'
            - '--machine-health-timeout=10m'
            - '--machine-safety-orphan-vms-period=30m'
            - '--machine-safety-overshooting-period=1m'
            - --node-conditions=ReadonlyFilesystem,KernelDeadlock,DiskPressure,NetworkUnavailable
            - '--v=2'
          resources: {}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10258
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
        - name: provider-openstack
          image: "registry.ske.eu01.stackit.cloud/gardener-ds/machine-controller-manager-provider-openstack:v0.3.0-ske-4-371e11a"
          imagePullPolicy: IfNotPresent
          command:
            - ./machine-controller
            - --control-kubeconfig=inClusterConfig
            - --namespace=machine-controller-manager
            - --port=10259
            - --v=3
            - --machine-creation-timeout=20m
            - --machine-drain-timeout=2h
            - --machine-health-timeout=10m
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 10259
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5            
      restartPolicy: Always
      serviceAccountName: machine-controller-manager
      serviceAccount: machine-controller-manager
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
---
# Source: mcm-deploy/templates/crs/machinedeployment.yaml
kind: MachineDeployment
apiVersion: machine.sapcloud.io/v1alpha1
metadata:
  name: worker-CHANGEME
  namespace: machine-controller-manager
spec:
  minReadySeconds: 600
  replicas: 2
  selector:
    matchLabels:
      deployment: CHANGEME
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: CHANGEME
    spec:
      class:
        kind: OpenStackMachineClass
        name: osclass-CHANGEME
